spring:
  freemarker:
    template-loader-path: classpath:/web/templates
    content-type: text/html
    charset: utf-8
    cache: false
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##